/**
 * Achievements.js — static definitions for the achievements viewer:
 * the trophy roster and the per-character unlock conditions. The earned
 * state and the awarding logic live in Game.js; this module only
 * describes what exists and how each thing reads on screen.
 */

/** Persistent trophies, in display order. `medal` is an emoji. */
export const TROPHIES = [
  { id: 'score50', medal: '🥉', title: 'Half Century', desc: 'Score 50 or more in a run.' },
  { id: 'score100', medal: '🥈', title: 'Ton Up', desc: 'Score 100 or more in a run.' },
  { id: 'score200', medal: '🏅', title: 'Double Ton', desc: 'Score 200 or more in a run.' },
  { id: 'score300', medal: '🥇', title: 'Triple Ton', desc: 'Score 300 or more in a run.' },
  { id: 'score400', medal: '🏆', title: 'Quadruple Ton', desc: 'Score 400 or more in a run.' },
  { id: 'score500', medal: '👑', title: 'Quintuple Ton', desc: 'Score 500 or more in a run.' },
  { id: 'score600', medal: '💎', title: 'Sextuple Ton', desc: 'Score 600 or more in a run.' },
  { id: 'decimal', medal: '🔢', title: 'Irrational', desc: 'Score a decimal (fractional) score.' },
  { id: 'tower3', medal: '⏰', title: 'Timekeeper', desc: 'Visit the clock tower 3 times in one run.' },
  { id: 'tower10', medal: '🕰️', title: 'Horologist', desc: 'Visit the clock tower 10 times in one run.' },
  { id: 'holeinone', medal: '⛳', title: 'Hole in One', desc: 'Sink a hole-in-one at Puttmost Respect.' },
  { id: 'tube', medal: '🚇', title: 'Mind the Gap', desc: 'Ride down to the Cottage Lane tube station.' },
  { id: 'lakebed', medal: '🫧', title: 'Deep Diver', desc: 'Reach the bottom of the lake (Marblella only).' },
  { id: 'star', medal: '⭐', title: 'Reach for the Stars', desc: 'Collect a star.' },
  { id: 'cloud', medal: '☁️', title: 'Up in the Clouds', desc: 'Collect a marshmallow cloud.' },
  { id: 'rip', medal: '💀', title: 'R.I.P.', desc: 'Let your health reach zero.' },
  { id: 'unlock1', medal: '🎭', title: 'Recruiter', desc: 'Unlock a character.' },
  { id: 'unlock5', medal: '🎪', title: 'Talent Scout', desc: 'Unlock 5 characters.' },
  { id: 'unlock10', medal: '🎡', title: 'Impresario', desc: 'Unlock 10 characters.' },
  { id: 'allstars', medal: '🌌', title: 'Star Cleaner', desc: 'Collect every star in a run.' },
  { id: 'allclouds', medal: '🌥️', title: 'Cloud Cleaner', desc: 'Collect every marshmallow cloud in a run.' },
  { id: 'allcherries', medal: '🍒', title: 'Cherry Cleaner', desc: 'Collect every atomic cherry in a run.' },
  { id: 'alleggs', medal: '🥇', title: 'Golden Sweep', desc: 'Collect every golden pine cone in a run.' },
  { id: 'allsky', medal: '🧹', title: 'Clean Sweep', desc: 'Clear all stars, cherries and clouds in one run.' },
  { id: 'train', medal: '🚆', title: 'Getting the Train', desc: 'Ride the Mystic Line from the ticket machine.' },
  { id: 'yoyo', medal: '🪀', title: 'Yo-Yo', desc: 'Cross 100 points up, down, up, down, up in one run.' },
  { id: 'c100', medal: '💯', title: 'C Unit', desc: 'Score 100 or more with 10 different characters.' },
  { id: 'c200', medal: '🌊', title: 'C Change', desc: 'Score 200 or more with 20 different characters.' },
  { id: 'c300', medal: '👋', title: 'C U Later', desc: 'Score 300 or more with 30 different characters.' },
  { id: 'play5', medal: '🎬', title: 'Repertory', desc: 'Play as 5 different characters.' },
  { id: 'play10', medal: '🎟️', title: 'Full Cast', desc: 'Play as 10 different characters.' },
  { id: 'play20', medal: '🎠', title: 'The Whole Menagerie', desc: 'Play as 20 different characters.' },
  { id: 'allstations', medal: '🚉', title: 'End of the Line', desc: 'Visit all three Mystic Line stations in one run.' },
  { id: 'firforest', medal: '🌲', title: 'Homecoming', desc: 'Take President Fir Tree into the Mystic Forest.' },
  { id: 'polarsummit', medal: '🐻‍❄️', title: 'Peak Bear', desc: 'Take Polar Pear to the mountain summit flag.' },
  { id: 'turnipwin', medal: '🐐', title: 'Kid vs Goat', desc: 'Beat Turnip Scart at Veggie Tac Toe while playing as Turnip Scart.' },
  { id: 'snooker', medal: '🎱', title: 'Snooker', desc: 'Score exactly 147 in a run, having collected one of every item type.' },
  { id: 'inapickle', medal: '🥒', title: 'In a Pickle', desc: 'Collect three pickles and score 303 or more in one run as Pickle Stick.' },
  { id: 'birdfeather', medal: '🐦', title: 'Bird of a Feather', desc: 'Clear every cherry and score over 250 as Perpendicular Bird.' },
  { id: 'woodlie', medal: '🪵', title: 'Wood I Lie To You', desc: 'Take Margaret or President Fir Tree to WOODOO’S with 50 health or less.' },
  { id: 'guava', medal: '🥝', title: 'Gather Guava, Wouldn’t You Rather', desc: 'Collect the Platinum Guava in a run.' },
  { id: 'hastings', medal: '🏹', title: 'Hastings Is A Place On Earth', desc: 'Grab both Magna Cartas as William the Conqueror and score exactly 106.6.' },
  { id: 'blisters', medal: '🎸', title: 'I’ve Got Blisters On My Fingers', desc: 'Reach the helter skelter with a score of 300 or more.' }
];

/** Every hero and the deed that earns them, in roster order. */
export const CHARACTER_UNLOCKS = [
  { key: 'badger', name: 'Badger', how: 'Your starting hero — always available.' },
  { key: 'badgerette', name: 'Badgerette', how: 'Finish a run with more than 30 points.' },
  { key: 'hughes', name: '‘Crisp Packet’ Hughes', how: 'Survive the full three minutes without taking a single hit.' },
  { key: 'boffington', name: 'Mr Finn Boffington', how: 'Bank 60 bonus seconds (six clock-tower visits) in one run.' },
  { key: 'william', name: 'William the Conqueror', how: 'Grab a Magna Carta.' },
  { key: 'edith', name: 'Edith McCombe', how: 'Take the hot air balloon up during a run.' },
  { key: 'rhombus', name: 'Rhombus the Hat', how: 'Finish on a score of exactly 90, 180, 270 or 360.' },
  { key: 'ginsberg', name: 'Alien Ginsberg', how: 'Collect five stars in one run.' },
  { key: 'magnus', name: 'Magnus Carter', how: 'Take four cart hits, survive the full run, and finish with 50+.' },
  { key: 'boddington', name: 'Mr Flynn Boddington', how: 'As Magnus, get run over by the cart twice in one run.' },
  { key: 'error42', name: 'Error #42', how: 'Collect one of every species in a run: cone, cherry, cloud, egg, star, Magna Carta.' },
  { key: 'mayo', name: 'Mayonnaise', how: 'Finish a run with 300+ points.' },
  { key: 'perpbird', name: 'Perpendicular Bird', how: 'As Mayonnaise, double-tap the BLT in the cave.' },
  { key: 'marblella', name: 'Marblella', how: 'Touch all four cottage fixtures (clock, stove, fridge, trap door) in one run.' },
  { key: 'fir', name: 'President Fir Tree', how: 'Jump three times inside the sealed Mystic Forest.' },
  { key: 'margaret', name: 'Margaret', how: 'In one run: 5 cherries, 4 clouds, 5 frog hits, and a final score ending in 4.' },
  { key: 'julie', name: 'Julie', how: 'Dismount from the rocket, the hovercraft AND the balloon in one run.' },
  { key: 'turnip', name: 'Turnip Scart', how: 'Beat the goat at Veggie Tac Toe on the vegetable patch (score a multiple of 7).' },
  { key: 'sweatshirt', name: 'Haunted Sweatshirt', how: 'Amass 30 achievements in total — trophies earned plus characters unlocked.' },
  { key: 'jam', name: 'Jam', how: 'Score an all-time total of 1000 points across every run.' },
  { key: 'dodeca', name: 'Dodecahedron the Beret', how: 'Finish a run with 300+ points while playing as Rhombus the Hat.' },
  { key: 'polarpear', name: 'Polar Pear', how: 'Reach the mountain summit flag on 10 health, then survive to the bell.' },
  { key: 'nighteye', name: 'Night Eye', how: 'Score an all-time total of 10000 points across every run.' },
  { key: 'pinepenguin', name: 'Pineapple Penguin', how: 'Reach the mountain summit flag with a score over 333.' },
  { key: 'billy', name: 'Billy Rocketfingers', how: 'Collect every star AND visit all three Mystic Line stations in one run.' },
  { key: 'pickle', name: 'Pickle Stick', how: 'Poke the cottage fridge 10 times, then collect the pickle that appears in a tree with a score of 100+.' },
  { key: 'glassbadger', name: 'Glass Badger', how: 'Score an all-time total of 20000 points across every run.' },
  { key: 'mcdonovan', name: 'McDonovan', how: 'Ride the Mystic Line all the way to Docklands.' },
  { key: 'prunella', name: 'Prunella Registered Voter', how: 'Finish a run having collected the same number of clouds as golden pine cones (at least one of each).' },
  { key: 'gary', name: 'Gary Mountain', how: 'Reach the mountain summit 100 times across all your runs (multiple summits in one run all count).' },
  { key: 'candy', name: 'Candy Florence', how: 'Visit the helter skelter 100 times across all your runs (multiple visits in one run all count).' }
];
