/**
 * Achievements.js — static definitions for the achievements viewer:
 * the trophy roster and the per-character unlock conditions. The earned
 * state and the awarding logic live in Game.js; this module only
 * describes what exists and how each thing reads on screen.
 */

/** Persistent trophies, in display order. `medal` is an emoji. */
export const TROPHIES = [
  { id: 'score50', medal: '🥉', title: 'Half Century', desc: 'Score 50 or more in a run.' },
  { id: 'score100', medal: '🥈', title: 'Ton Up', desc: 'Score 100 or more in a run.' },
  { id: 'score200', medal: '🏅', title: 'Double Ton', desc: 'Score 200 or more in a run.' },
  { id: 'score300', medal: '🥇', title: 'Triple Ton', desc: 'Score 300 or more in a run.' },
  { id: 'score400', medal: '🏆', title: 'Quadruple Ton', desc: 'Score 400 or more in a run.' },
  { id: 'score500', medal: '👑', title: 'Quintuple Ton', desc: 'Score 500 or more in a run.' },
  { id: 'score600', medal: '💎', title: 'Sextuple Ton', desc: 'Score 600 or more in a run.' },
  { id: 'decimal', medal: '🔢', title: 'Irrational', desc: 'Score a decimal (fractional) score.' },
  { id: 'tower3', medal: '⏰', title: 'Timekeeper', desc: 'Visit the clock tower 3 times in one run.' },
  { id: 'tower10', medal: '🕰️', title: 'Horologist', desc: 'Visit the clock tower 10 times in one run.' },
  { id: 'holeinone', medal: '⛳', title: 'Hole in One', desc: 'Sink a hole-in-one at Puttmost Respect.' },
  { id: 'tube', medal: '🚇', title: 'Mind the Gap', desc: 'Ride down to the Cottage Lane tube station.' },
  { id: 'lakebed', medal: '🫧', title: 'Deep Diver', desc: 'Reach the bottom of the lake (Marblella only).' },
  { id: 'star', medal: '⭐', title: 'Reach for the Stars', desc: 'Collect a star.' },
  { id: 'cloud', medal: '☁️', title: 'Up in the Clouds', desc: 'Collect a marshmallow cloud.' },
  { id: 'rip', medal: '💀', title: 'R.I.P.', desc: 'Let your health reach zero.' },
  { id: 'unlock1', medal: '🎭', title: 'Recruiter', desc: 'Unlock a character.' },
  { id: 'unlock5', medal: '🎪', title: 'Unlocked, High Five!', desc: 'Unlock 5 characters.' },
  { id: 'unlock10', medal: '🎡', title: 'Unlock It In A Docket', desc: 'Unlock 10 or more characters.' },
  { id: 'unlock20', medal: '🎢', title: 'Unlock It In Your Pocket', desc: 'Unlock 20 or more characters.' },
  { id: 'unlock50', medal: '🚪', title: "Unlock, Lock, Locking On Heaven's Door", desc: 'Unlock 50 or more characters.' },
  { id: 'unlockroll', medal: '🎳', title: "Unlock 'N' Roll", desc: 'Unlock a character who rolls or slides rather than walking.' },
  { id: 'allstars', medal: '🌌', title: 'Star Cleaner', desc: 'Collect every star in a run.' },
  { id: 'allclouds', medal: '🌥️', title: 'Cloud Cleaner', desc: 'Collect every marshmallow cloud in a run.' },
  { id: 'allcherries', medal: '🍒', title: 'Cherry Cleaner', desc: 'Collect every atomic cherry in a run.' },
  { id: 'alleggs', medal: '🥇', title: 'Golden Sweep', desc: 'Collect every golden pine cone in a run.' },
  { id: 'allsky', medal: '🧹', title: 'Clean Sweep', desc: 'Clear all stars, cherries and clouds in one run.' },
  { id: 'train', medal: '🚆', title: 'Getting the Train', desc: 'Ride the Mystic Line from the ticket machine.' },
  { id: 'yoyo', medal: '🪀', title: 'Yo-Yo', desc: 'Cross 100 points up, down, up, down, up in one run.' },
  { id: 'c100', medal: '💯', title: 'C Unit', desc: 'Score 100 or more with 10 different characters.' },
  { id: 'c200', medal: '🌊', title: 'C Change', desc: 'Score 200 or more with 20 different characters.' },
  { id: 'c300', medal: '👋', title: 'C U Later', desc: 'Score 300 or more with 30 different characters.' },
  { id: 'c400', medal: '🛬', title: 'C U When You Get There', desc: 'Score 400 or more with 40 different characters.' },
  { id: 'play5', medal: '🎬', title: 'Repertory', desc: 'Play as 5 different characters.' },
  { id: 'play10', medal: '🎟️', title: 'Full Cast', desc: 'Play as 10 different characters.' },
  { id: 'play20', medal: '🎠', title: 'The Whole Menagerie', desc: 'Play as 20 different characters.' },
  { id: 'allstations', medal: '🚉', title: 'End of the Line', desc: 'Visit three Mystic Line stations in one run.' },
  { id: 'mondrian', medal: '🎨', title: 'More Lines Than Mondrian', desc: 'Visit all four Mystic Line stations in one run and complete a painting in Neptune’s Nook.' },
  { id: 'firforest', medal: '🌲', title: 'Homecoming', desc: 'Take President Fir Tree into the Mystic Forest.' },
  { id: 'polarsummit', medal: '🐻‍❄️', title: 'Peak Bear', desc: 'Take Polar Pear to the mountain summit flag.' },
  { id: 'turnipwin', medal: '🐐', title: 'Kid vs Goat', desc: 'Beat Turnip Scart at Veggie Tac Toe while playing as Turnip Scart.' },
  { id: 'snooker', medal: '🎱', title: 'Snooker', desc: 'Score exactly 147 in a run, having collected one of every item type.' },
  { id: 'inapickle', medal: '🥒', title: 'In a Pickle', desc: 'Collect three pickles and score 303 or more in one run as Pickle Stick.' },
  { id: 'birdfeather', medal: '🐦', title: 'Bird of a Feather', desc: 'Clear every cherry and score over 250 as Perpendicular Bird.' },
  { id: 'woodlie', medal: '🪵', title: 'Wood I Lie To You', desc: 'Take Margaret or President Fir Tree to WOODOO’S with 50 health or less.' },
  { id: 'guava', medal: '🥝', title: 'Gather Guava, Wouldn’t You Rather', desc: 'Collect the Platinum Guava in a run.' },
  { id: 'hastings', medal: '🏹', title: 'Hastings Is A Place On Earth', desc: 'Grab both Magna Cartas as William the Conqueror and score exactly 106.6.' },
  { id: 'blisters', medal: '🎸', title: 'I’ve Got Blisters On My Fingers', desc: 'Reach the helter skelter with a score of 300 or more.' },
  { id: 'whirlylucky', medal: '🍀', title: 'Whirly Lucky', desc: 'Get three positive whirlpool scores in a row in one run.' },
  { id: 'inaspin', medal: '😵‍💫', title: 'In A Spin', desc: 'Get three negative whirlpool scores in a row in one run.' },
  { id: 'chimptactoe', medal: '🍌', title: 'Chimp Tac Toe', desc: 'Beat Turnip Scart at Veggie Tac Toe as Chimpy Henderson and finish on a multiple of 7.' },
  { id: 'owlin4u', medal: '🦉', title: 'Owlin’ 4 U', desc: 'Score 400 or more as Pastry Owl between 21:00 and 23:59 (local time).' },
  { id: 'afk', medal: '💤', title: 'AFK?', desc: 'Finish a run above zero without collecting a single item.' },
  { id: 'plattytubes', medal: '🥝', title: 'Platty Tubes', desc: 'Ride the Mystic Line to a station and collect the Platinum Guava in the same run.' },
  { id: 'lifeaquatic', medal: '🌊', title: 'Life Aquatic', desc: 'Finish a run out on the water of one of the lakes.' },
  { id: 'afkc', medal: '😴', title: 'AFKC', desc: 'Finish a run on 100 or more without collecting a single item.' },
  { id: 'charredmeander', medal: '🍳', title: 'Charred Meander', desc: 'Cook a charred pickle fritter: carry the pan from Neptune’s Nook, catch a pickle in it, and fry it on the cottage stove.' },
  { id: 'farmervspig', medal: '🐖', title: 'Farmer vs Pig', desc: 'Complete a run as both Robo-Farmer and Bacon.' },
  { id: 'mysticsquared', medal: '🔲', title: 'Mystic Squared', desc: 'Complete a run with a Mystic (monochrome) run active.' },
  { id: 'frogs50', medal: '🐸', title: 'Frogs!', desc: 'Take more than 50 toxic frog hits across all your runs.' },
  { id: 'frogs100', medal: '🐸', title: 'FROGS!!!!', desc: 'Take more than 100 toxic frog hits across all your runs.' },
  { id: 'mysticcubed', medal: '🧊', title: 'Mystic Cubed', desc: 'Complete a Mystic (monochrome) run having ridden the Mystic Line to Mystic Forest Central on that same run.' },
  { id: 'pointproved', medal: '☝️', title: 'Point Proved', desc: 'Score your first ever point.' },
  { id: 'lifetime10k', medal: '🔟', title: 'Lifetime M10', desc: 'Score an all-time total of more than 10,000 points across every run.' },
  { id: 'lifetime50k', medal: '🏔️', title: 'Lifetime M50', desc: 'Score an all-time total of more than 50,000 points across every run.' },
  { id: 'lifetime100k', medal: '🌟', title: 'Lifetime M100', desc: 'Score an all-time total of more than 100,000 points across every run.' },
  { id: 'frogspawn', medal: '🐸', title: 'Frog Spawn', desc: 'As Sir Frosch, take damage from more than one frog and finish the run on 400 or more.' },
  { id: 'zapped', medal: '⚡', title: 'Zapped!', desc: 'Let the transmission tower take your health to zero during a storm.' },
  { id: 'antizapped', medal: '🔌', title: 'Anti-Zapped', desc: 'Take the tower\u2019s +40 as Error #42, Error #43 or the Haunted Sweatshirt \u2014 the four heroes it feeds instead of frying.' },
  { id: 'play40', medal: '🎢', title: 'Standing Room Only', desc: 'Play as 40 different characters.' },
  { id: 'total50', medal: '🏵️', title: 'Half Centurion', desc: 'Amass 50 achievements in total — trophies earned plus characters unlocked.' },
  { id: 'total100', medal: '🎖️', title: 'Centurion', desc: 'Amass 100 achievements in total — trophies earned plus characters unlocked.' },
  { id: 'doppelganger', medal: '🔴', title: 'Feathered Doppelgänger', desc: 'Complete a run as W. Wolk — as P. Cork with the weather against you, or as the red bird himself.' },
  { id: 'charredishard', medal: '🍳', title: 'Charred Is Hard', desc: 'Cook a charred pickle fritter AND finish that same run on a whole number. The fritter pays 88.8, so you will need another fraction to complete it.' },
  { id: 'boffline', medal: '🎟️', title: 'Boffington\'s Travelcard', desc: 'As Finn Boffington or Flynn Boddington: ride the Mystic Line to all FOUR stations in one run.' },
  { id: 'starbilly', medal: '🌟', title: 'Fingers On The Buzzer', desc: 'As Billy Rocketfingers or Alien Ginsberg: collect every star AND finish on 400 or more in one run.' },
  { id: 'garyair', medal: '🪂', title: 'Gary Takes The Air', desc: 'As Gary Mountain: reach the mountain summit by balloon or rocket rather than climbing it.' },
  { id: 'candyslide', medal: '🎡', title: 'Florence Goes Round Again', desc: 'As Candy Florence: ride the helter skelter.' },
  { id: 'nellyfive', medal: '📉', title: 'Told You So', desc: 'As Negative Nelly: take FIVE negative whirlpool spins in the same run.' },
  { id: 'parsleyout', medal: '🌿', title: 'Get That Parsley Out Of Here', desc: 'As Parsley O’Riley: reach the cave’s BLT with 500 or more, and be told exactly where to go.' },
  { id: 'crisps', medal: '🥔', title: 'Always Better With Crisps', desc: 'As ‘Crisp Packet’ Hughes: reach the cave’s BLT with 400 or more. Worth +40.' },
  { id: 'mcdcoffee', medal: '☕', title: 'The Usual', desc: 'As McDonovan: visit the coffee cart. A private eye runs on it.' },
  { id: 'taradouble', medal: '🥒', title: 'Twice The Pickle', desc: 'As Tara Tapir: collect a pickle while her double-pickle deal is running.' },
  { id: 'prettyweird', medal: '👾', title: 'These Guys Are Pretty Weird', desc: 'Complete a run as all four of Postboxer, Edith McCombe, Prunella Registered Voter and Ol’ Cardboard Box.' },
  { id: 'fedora180', medal: '🎯', title: 'One Hundred And Eighty', desc: 'As Triangle the Fedora: finish on EXACTLY 180, with no balloon and no rocket all run.' },
  { id: 'nemesis', medal: '😈', title: 'Nemesis', desc: 'As Wagnus Warter: get run over by the golf cart. The cart knows what he did.' },
  { id: 'nucleustime', medal: '⏳', title: 'All The Time In The World', desc: 'As The Nucleus Of Time Itself: visit the clock tower 5 or more times and finish on 300 or more.' },
  { id: 'laika', medal: '🛰️', title: 'Laika’s Return', desc: 'As Julie: ride the rocket, collect every star, take the Platinum Guava, and finish the run back on solid ground.' },
];

/** Every hero and the deed that earns them, in roster order. */
export const CHARACTER_UNLOCKS = [
  { key: 'badger', name: 'Badger', how: 'Your starting hero — always available.' },
  { key: 'badgerette', name: 'Badgerette', how: 'Finish a run with more than 30 points.' },
  { key: 'hughes', name: '‘Crisp Packet’ Hughes', how: 'Survive the full three minutes without taking a single hit.' },
  { key: 'boffington', name: 'Mr Finn Boffington', how: 'Bank 60 bonus seconds (six clock-tower visits) in one run.' },
  { key: 'william', name: 'William the Conqueror', how: 'Grab a Magna Carta.' },
  { key: 'edith', name: 'Edith McCombe', how: 'Take the hot air balloon up during a run.' },
  { key: 'rhombus', name: 'Rhombus the Hat', how: 'Finish on a score of exactly 90, 180, 270 or 360.' },
  { key: 'ginsberg', name: 'Alien Ginsberg', how: 'Collect five stars in one run.' },
  { key: 'magnus', name: 'Magnus Carter', how: 'Take four cart hits, survive the full run, and finish with 50+.' },
  { key: 'boddington', name: 'Mr Flynn Boddington', how: 'As Magnus, get run over by the cart twice in one run.' },
  { key: 'error42', name: 'Error #42', how: 'Collect one of every species in a run: cone, cherry, cloud, egg, star, Magna Carta.' },
  { key: 'mayo', name: 'Mayonnaise', how: 'Finish a run with 300+ points.' },
  { key: 'perpbird', name: 'Perpendicular Bird', how: 'As Mayonnaise, double-tap the BLT in the cave.' },
  { key: 'marblella', name: 'Marblella', how: 'Touch all four cottage fixtures (clock, stove, fridge, trap door) in one run.' },
  { key: 'fir', name: 'President Fir Tree', how: 'Jump three times inside the sealed Mystic Forest.' },
  { key: 'margaret', name: 'Margaret', how: 'In one run: 5 cherries, 4 clouds, 5 frog hits, and a final score ending in 4.' },
  { key: 'julie', name: 'Julie', how: 'Dismount from the rocket, the hovercraft AND the balloon in one run.' },
  { key: 'turnip', name: 'Turnip Scart', how: 'Beat the goat at Veggie Tac Toe on the vegetable patch (score a multiple of 7).' },
  { key: 'sweatshirt', name: 'Haunted Sweatshirt', how: 'Amass 30 achievements in total — trophies earned plus characters unlocked.' },
  { key: 'jam', name: 'Jam', how: 'Score an all-time total of 1000 points across every run.' },
  { key: 'dodeca', name: 'Dodecahedron the Beret', how: 'Finish a run with 300+ points while playing as Rhombus the Hat.' },
  { key: 'polarpear', name: 'Polar Pear', how: 'Reach the mountain summit flag on 10 health, then survive to the bell.' },
  { key: 'nighteye', name: 'Night Eye', how: 'Score an all-time total of 10000 points across every run.' },
  { key: 'pinepenguin', name: 'Pineapple Penguin', how: 'Reach the mountain summit flag with a score over 333.' },
  { key: 'billy', name: 'Billy Rocketfingers', how: 'Collect every star AND visit all three Mystic Line stations in one run.' },
  { key: 'pickle', name: 'Pickle Stick', how: 'Poke the cottage fridge 10 times, then collect the pickle that appears in a tree with a score of 100+.' },
  { key: 'glassbadger', name: 'Glass Badger', how: 'Score an all-time total of 20000 points across every run.' },
  { key: 'mcdonovan', name: 'McDonovan', how: 'Ride the Mystic Line all the way to Docklands.' },
  { key: 'prunella', name: 'Prunella Registered Voter', how: 'Finish a run having collected the same number of clouds as golden pine cones (at least one of each).' },
  { key: 'gary', name: 'Gary Mountain', how: 'Reach the mountain summit 100 times across all your runs (multiple summits in one run all count).' },
  { key: 'candy', name: 'Candy Florence', how: 'Visit the helter skelter 100 times across all your runs (multiple visits in one run all count).' },
  { key: 'cactusballoon', name: 'Cactus Balloon', how: 'Ride the hovercraft, the rocket AND the balloon in one run, then take the Mystic Line to Cactus Junction.' },
  { key: 'nelly', name: 'Negative Nelly', how: 'Finish a run with a negative score.' },
  { key: 'trifedora', name: 'Triangle the Fedora', how: 'As Rhombus the Hat or Dodecahedron the Beret: beat Turnip Scart at Veggie Tac Toe AND sink a hole-in-one in the same run.' },
  { key: 'parsley', name: "Parsley O'Riley", how: "Reach the cave's BLT with 300+ points, having used the balloon as your ONLY transport that run (no hovercraft, rocket or train)." },
  { key: 'vapour', name: 'Vapour Badger', how: 'Score an all-time total of 40,000 points across every run.' },
  { key: 'spirit', name: 'Spirit of the Forest Badger', how: 'Score an all-time total of 100,000 points across every run.' },
  { key: 'chimpy', name: 'Chimpy Henderson', how: 'In one run: claim Red October (strike the submarine) AND take the Mystic Line to Docklands — all without using the hovercraft.' },
  { key: 'owl', name: 'Pastry Owl', how: 'Score 300+ with at least five clouds collected, between 21:00 and 23:59 (local time).' },
  { key: 'snappy', name: 'Top Hat Snappy', how: 'Enter the whirlpool 100 times across all your runs (multiple dips in one run all count).' },
  { key: 'bacon', name: 'Bacon', how: 'Dress the cave BLT with every sandwich hero (Mayonnaise, Jam and Chimpy Henderson) — across any runs.' },
  { key: 'robofarmer', name: 'Robo-Farmer', how: 'In one run: reach 231 points AND beat Turnip Scart at Veggie Tac Toe.' },
  { key: 'frosch', name: 'Sir Frosch', how: 'Take 101 toxic frog hits across all your runs. Leaps nine times as high as anyone else — but ambles at half speed.' },
  { key: 'error43', name: 'Error #43', how: 'She turns up on 4.3% of Random-Character runs from the very beginning, unlocked or not. Finish one of those runs on 250 or more and she joins the roster for good.' },
  { key: 'nucleus', name: 'The Nucleus Of Time Itself', how: 'Bank enough bonus seconds in one run to double its length to six minutes — 180 extra seconds (eighteen clock-tower visits, or sixteen plus the cottage alarm).' },
  { key: 'tudor', name: 'Tudor Lizard', how: 'Finish a run on a perfectly round hundred — 100, 200, 300, 400, 500…' },
  { key: 'electro', name: 'Electro Badger', how: 'Playing as any badger, walk into the live transmission tower during a storm on a score of 400 or more and let it take you to zero health.' },
  { key: 'foil', name: 'Foil', how: 'In one run: open the cottage fridge, and clear every marshmallow cloud AND every star.' },
  { key: 'error44', name: 'Error #44', how: 'Complete a run in Mystic mode — the rare monochrome wash.' },
  { key: 'cardboard', name: "Ol' Cardboard Box", how: 'Board the rocket twice in the same run.' },
  { key: 'tapir', name: 'Tara Tapir', how: 'In one run: cook the charred pickle fritter, collect Neptune\u2019s Raisin, use no transport at all (no hovercraft, balloon, rocket or train) and finish on 200 or more.' },
  { key: 'postboxer', name: 'Postboxer', how: 'Score 400 or more as all three Errors \u2014 #42, #43 and #44 \u2014 across any runs.' },
  { key: 'pcork', name: 'P. Cork', how: 'Tap the Bass Moultapps logo on the About page with a lifetime score of 1,000 or more.' },
  { key: 'wolk', name: 'W. Wolk', how: 'Playing as W. Wolk \u2014 that is, as P. Cork with the weather against you \u2014 enter the whirlpool on a score of 200 or more.' },
  { key: 'muffin', name: "Neptune's Muffin", how: "Collect 20 Neptune's Raisins across all your runs (one is hidden in the cottage loft each run)." },
  { key: 'error45', name: 'Error #45', how: 'Finish a run on a PRIME NUMBER score while playing as Error #42, #43 or #44.' },
  { key: 'wagnus', name: 'Wagnus Warter', how: 'Get run over by the golf cart 6 times in one run, survive to the bell, and finish on more than 50.' },
  { key: 'reindeer', name: 'Raspberry Reindeer', how: 'Complete a run on full health as Pineapple Penguin or Polar Pear, in SNOW.' }
];
